// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfHyVkvgHZbMRcDJ8bqMoLNr4qMBRgxRw',
    appId: '1:888682548682:web:98090a7ee57cf2afa21333',
    messagingSenderId: '888682548682',
    projectId: 'findaid-f0766',
    authDomain: 'findaid-f0766.firebaseapp.com',
    storageBucket: 'findaid-f0766.appspot.com',
    measurementId: 'G-C1RRZ5F3TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh6MG415pNeEFRQje-qe-DrYiXFo24FXk',
    appId: '1:888682548682:android:276d0519902b4dfaa21333',
    messagingSenderId: '888682548682',
    projectId: 'findaid-f0766',
    storageBucket: 'findaid-f0766.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFBVxd7IH_n-mJ32DFlZtF_Rhfsfs5sDc',
    appId: '1:888682548682:ios:9e4ef99615522bd7a21333',
    messagingSenderId: '888682548682',
    projectId: 'findaid-f0766',
    storageBucket: 'findaid-f0766.appspot.com',
    iosBundleId: 'com.findaid.findaid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFBVxd7IH_n-mJ32DFlZtF_Rhfsfs5sDc',
    appId: '1:888682548682:ios:95b1c0675e543fe3a21333',
    messagingSenderId: '888682548682',
    projectId: 'findaid-f0766',
    storageBucket: 'findaid-f0766.appspot.com',
    iosBundleId: 'com.findaid.findaid.RunnerTests',
  );
}
